### ISSUE TITLE
Running WMImplant

### ISSUE THREAD

**Issue by aalborz** [ChrisTruncer/WMImplant#16]
I downloaded the script. I'm getting an error when trying to run Invoke-WMImplant in PS ISE. It says it is not recognized as the name of a cmdlet, function, script file, or operable program.

**Comment by roobixx** [comment]
try importing as a module.

Import-Module <path\to\file\WMImplant.ps1>

**Comment by aalborz** [comment]
Thanks, I did . .\WMImplant.ps1 & it worked.
